# Generated by Django 3.2 on 2021-05-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prooerty_name', models.CharField(max_length=40, verbose_name='物件名')),
                ('address1', models.CharField(choices=[('東京都', '東京都')], max_length=10, verbose_name='住所１')),
                ('address2', models.CharField(choices=[('新宿区', '新宿区'), ('渋谷区', '渋谷区'), ('目黒区', '目黒区')], max_length=10, verbose_name='住所２')),
                ('address3', models.CharField(max_length=20, verbose_name='住所３')),
                ('nearest_sta1', models.CharField(choices=[('新宿', '新宿'), ('代々木', '代々木'), ('原宿', '原宿'), ('渋谷', '渋谷'), ('恵比寿', '恵比寿')], max_length=6, verbose_name='最寄り駅１')),
                ('min_walk_from_sta1', models.IntegerField(max_length=3, verbose_name='駅１徒歩')),
                ('area', models.FloatField(max_length=10, verbose_name='面積')),
                ('layout', models.CharField(choices=[('1R', '1R'), ('1K', '1K'), ('1LDK', '1LDK'), ('2LDK', '2LDK'), ('3LDK', '3LDK')], max_length=10, verbose_name='間取り')),
                ('is_separated', models.BooleanField(choices=[(True, 'バストイレ別'), (False, 'ユニットバス')], verbose_name='バストイレ')),
                ('has_indoor_laundry_space', models.BooleanField(choices=[(True, '室内洗濯機置場あり'), (False, '室内洗濯機置場なし')], verbose_name='室内洗濯機置場')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真１')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'RentalProperty',
            },
        ),
    ]
