# Generated by Django 3.2 on 2021-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='min_walk_from_sta1',
            field=models.IntegerField(verbose_name='駅１徒歩'),
        ),
    ]
