# Generated by Django 3.2 on 2021-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_rentalproperty_min_walk_from_sta1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='rent',
            field=models.IntegerField(default=100000, verbose_name='賃料'),
            preserve_default=False,
        ),
    ]
